add_newline = false
scan_timeout = 1000

format = """
[╭─](fg:#ffb3e0)$directory$git_branch$git_status$python$cmd_duration
[╰─❯](fg:#ffb3e0) """

[directory]
style = "bold fg:#ffd6ee"
format = "[ 󰉋 $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "doc"
"Downloads" = "dl"
"Music" = "music"
"Pictures" = "pic"

[git_branch]
format = '[ 󰊢 $branch](fg:#ffc8e8)'

[git_status]
format = '([$all_status$ahead_behind ](fg:#ff5c8a))'
conflicted = "!"
untracked = "?"
modified = "~"
staged = "+"
deleted = "-"
ahead = "⇡$count"
behind = "⇣$count"

[python]
format = '[ 󰌠 $version](fg:#d8b4f0)'
version_format = "${raw}"

[cmd_duration]
format = '[ 󱑃 $duration](fg:#e0a0d8)'
min_time = 2000
